Added integration test and cleaned logic
AITestingOrg/semantic-network pull request #1
Opened 2018-01-31 20:32 UTC by R4il

2018-02-06 23:01 UTC, Castyr commented on src/main/java/aist/incremental/learning/IGeneralizationStrategy.java
> +    boolean findIfRelationExists(String value1, String value2, String rel);
I'm assuming value1 and value2 are the nodes here, you should name them a bit better.

2018-02-06 23:10 UTC, Castyr requested changes
Overall good job, just look at the comments I have put in.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
> +        driver.session().close();
Does session extend from AutoCloseable, if so I would consider using automatic resource block management here, IE "using" for Java. It would clean up the open and close of the session.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
>          if (!res.hasNext()) {
Can't you just call next here, then check for a null? That seems cleaner.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
> +                parameters("value", value));
Use constants instead of these implicit strings.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
> +    public List<IPath> checkGeneralizedConnection(String from, String to, String rel) {
All of these methods with more complicated queries should get some comments explaining the logic.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
>      public void updateRelationships(String oldRel, String newRel) {
Don't abbreviate the arguments.

2018-02-06 23:10 UTC, Castyr commented on src/main/java/neo4j/Neo4jDriverAdapter.java
> +        System.out.println("Running query:" + query);
Print lines need to go, replace them with Log.debug if you must.

2018-02-07 14:22 UTC, R4il commented on src/main/java/neo4j/Neo4jDriverAdapter.java
> +        driver.session().close();
Extends Resource which extends AutoCloseable. So I guess yes.

2018-02-07 15:05 UTC, R4il commented on src/main/java/neo4j/Neo4jDriverAdapter.java
>          if (!res.hasNext()) {
Calling next wont return null if there are no records, it will throw a NoSuchRecordException. When I was just looking for a Node I did not want to be throwing that, I just wanted to return null if the node isnt found in the db. I could do try/catch, but since we said never to hide exceptions I decided to do this.

2018-02-08 02:30 UTC, Castyr approved these changes

2018-05-08 17:55 UTC, merged